# -*- coding: utf-8 -*-
"""CEPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S4kc5ULg9uFcN76JU4lfz81hANcFzg3n
"""

def tijolo(valor01,valor02) :
  print(" Aqui é o número : " + str(valor01) + str(valor02))

tijolo(12,"Angel")
tijolo(15, "hello")
tijolo(22,44)

import requests

def lala() :
  print('CEPython')
  cep = input('Digite o CEP para a consulta; ')

  while len(cep) != 8 :
    print('Quantidade de dígitos inválida!')
    cep = input('Digite o CEP para a consulta: ')




  caixinha = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco = caixinha.json()
  #print(endereco)
  if 'erro' not in endereco:
    print('==> CEP ENCONTRADO <==')
    print("CEP: " + endereco ['cep'] )
    print('Cidade: {}' .format(endereco['localidade']))
    print(f"Estado: {endereco['uf']}")

  else:
    print('{}: CEP inválido.' .format(cep))

  print('----------------------------------')   

  def validacao():
    opcao = input('Deseja realizar outra consulta ? \n 1 Sim\ n 2 sair \n')
    if opcao == "1" or opcao == "2" :
      if int(opcao) == 1:
        lala()
      else:
        print('Até Mais!!!')
    else:
      print("Não entendi!!!")
      validacao()
  validacao()



  

lala()